In [1]:
#%matplotlib inline
import numpy as np
#import faultdiagnosistoolbox as fdt
import faultdiagnosistoolbox.diagnosismodel as fdt

In [2]:
reload(fdt);
dir(fdt)

['DiagnosisModel',
 'ModelStructure',
 'RelModelStructure',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 'np']

In [3]:
modeldef = {}
modeldef['rels']= [['Ps', 'xf10', 'x', 'f4', 'f11', 'Fvc'],
    ['xh', 'x', 'f8'],
    ['Qv', 'f5', 'f1', 'xh', 'DeltaP'],
    ['DeltaP-a', 'xh', 'P1', 'Pv'],
    ['Pv', 'T1'],
    ['DeltaP', 'P1', 'P2', 'DeltaP-a'],
    ['Fvc', 'P1', 'xh', 'P2', 'DeltaP-a','Pv'],
    ['Qv3', 'x3', 'f18', 'P1', 'P2'],
    ['Qc', 'Ps', 'xh'],
    ['Qc', 'f9', 'Ps', 'xf10', 'CVI', 'Pz', 'f16'],
    ['Q', 'Qv', 'Qv3'],
    ['Yx', 'xh', 'f13'],
    ['YP1', 'P1'],
    ['YP2', 'P2'],
    ['T1', 'f7'],
    ['CVI', 'f12', 'Cv', 'Yx'],
    ['xf10', 'f10']]
modeldef['type'] = 'VarStruc'
modeldef['x'] = ['x', 'xh', 'Ps', 'P1', 'P2', 'Pz','Pv', 'DeltaP', 
    'DeltaP-a', 'Q', 'Qv', 'Qv3', 'Qc', 'T1', 'Fvc', 'xf10']
modeldef['f'] = ['f1', 'f4', 'f5', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 
    'f13', 'f16', 'f18']
modeldef['z'] = ['Yx', 'YP1', 'YP2', 'CVI', 'Cv', 'x3']
model=fdt.DiagnosisModel( modeldef )

In [4]:
print model.x
print model.X

['x', 'xh', 'Ps', 'P1', 'P2', 'Pz', 'Pv', 'DeltaP', 'DeltaP-a', 'Q', 'Qv', 'Qv3', 'Qc', 'T1', 'Fvc', 'xf10']
[[ 1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1

In [5]:
model.PlotModel();

AttributeError: 'DiagnosisModel' object has no attribute 'PlotModel'

In [10]:
import matplotlib as mpl
mpl.use('TkAgg')
import matplotlib.pyplot as plt

In [11]:
import scipy.sparse as sp
dir(sp)

['SparseEfficiencyWarning',
 'SparseWarning',
 'Tester',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '_csparsetools',
 '_sparsetools',
 'absolute_import',
 'base',
 'bench',
 'block_diag',
 'bmat',
 'bsr',
 'bsr_matrix',
 'compressed',
 'construct',
 'coo',
 'coo_matrix',
 'cs_graph_components',
 'csc',
 'csc_matrix',
 'csgraph',
 'csr',
 'csr_matrix',
 'data',
 'dia',
 'dia_matrix',
 'diags',
 'division',
 'dok',
 'dok_matrix',
 'extract',
 'eye',
 'find',
 'hstack',
 'identity',
 'issparse',
 'isspmatrix',
 'isspmatrix_bsr',
 'isspmatrix_coo',
 'isspmatrix_csc',
 'isspmatrix_csr',
 'isspmatrix_dia',
 'isspmatrix_dok',
 'isspmatrix_lil',
 'kron',
 'kronsum',
 'lil',
 'lil_matrix',
 'print_function',
 'rand',
 'random',
 's',
 'spdiags',
 'spmatrix',
 'sputils',
 'test',
 'tril',
 'triu',
 'vstack']